HallOfFame/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url


urlpatterns = [
    path('admin/', admin.site.urls),

    # authentication
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('courses.urls')),

    # general viewing of details
    path('courses/', include('courses.urls')),  # list of courses
    path('courses/<int:course_id>', include('courses.urls')),  # list of groups in course with possibility to join (students only), view, search, create (teachers only)
    path('courses/<int:course_id>/<int:group_id>', include('courses.urls')),  # group details
    path('courses/<int:course_id>/<int:group_id>/<int:event_id>', include('courses.urls')),  # event details for group participants only
    path('courses/<int:course_id>/<int:group_id>/grades', include('courses.urls')),  # table of grades
    path('courses/<int:course_id>/<int:group_id>/events', include('courses.urls')),  # events divided for past and upcomming
    path('courses/myGrades', include('courses.urls')),  # list of grades from all courses (students only)

    path('courses/group/<int:group_id>', include('courses.urls')),


    # marking (for teachers only)
    path('courses/<int:course_id>/<int:group_id>/<int:event_id>/addGrades', include('courses.urls')),  # adding grades for event

    # creating (for teachers only)
    path('courses/createCourse', include('courses.urls')),  # create course form
    path('courses/<int:course_id>/createGroup', include('courses.urls')),  # create group form
    path('courses/<int:course_id>/<int:group_id>/createEvent', include('courses.urls')),  # create event in group form
    url(r'^courses/group/<int:group_id', include('courses.urls', namespace='HallOfFame'))

]

courses/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = "HallOfFame"

urlpatterns = [
    path('', views.index, name='index'),
    path('', views.search, name='index'),

    path('accounts/signupStudent', views.signup_student, name='signup'),
    path('accounts/signupTeacher', views.signup_teacher, name='signup'),
    path('accounts/', views.pick_register, name='register_pick'),

    path('<int:course_id>', views.course, name='course'),
    path('group/<int:group_id>', views.group, name='group'),  # group details
    path('<int:course_id>/<int:group_id>/<int:event_id>', views.blank, name='blank'),
    path('<int:course_id>/<int:group_id>/grades', views.blank, name='blank'),  # table of grades
    path('<int:course_id>/<int:group_id>/events', views.blank, name='blank'),
    path('addGrades/<int:event_id>', views.add_grades, name='add_grades'),
    path('createCourse', views.create_course, name='create_course'),
    path('<int:course_id>/createGroup', views.create_group, name='create_group'),
    path('group/<int:group_id>/createEvent', views.create_event, name='create_event'),
    path('createTasks/<int:event_id>/<int:tasks_count>', views.create_event_tasks, name='create_tasks'),
    path('myGrades', views.blank, name='blank'),
    path('group/<int:group_id>/join', views.join, name='join'),

    path('uploadGrades/<int:event_id>', views.upload_grades, name='upload_grades'),
    path('confirmUpload/<int:event_id>/<path:csv_file_path>', views.confirm_upload, name='confirm_upload'),
    path('cancelUpload/<int:event_id>/<path:csv_file_path>', views.cancel_upload, name='cancel_upload'),
    path('myUpcomingEvents/', views.upcoming_events, name='upcoming_events'),
    path('myGrades/', views.grades, name='grades'),
]

courses/models.py
from django.db import models
from django.db.models import Sum, Avg, Max, Variance
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
from statistics import mean, median, variance
from math import isnan



# Create your models here.
GRADES = (
    ('2.0', '2.0'),
    ('3.0', '3.0'),
    ('3.5', '3.5'),
    ('4.0', '4.0'),
    ('4.5', '4.5'),
    ('5.0', '5.0'),
)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    student_card_id = models.CharField(max_length=16)

    def __str__(self):
        return self.user.get_full_name()

    def calculate_current_final(self, group_id):
        grades = self.grade_set.filter(event__group_id=group_id)

        if not any(grades):
            return 'No grades so far'

        grades_for_events_required_to_pass = grades.filter(event__is_required_to_pass_the_course=True)
        if any(grades_for_events_required_to_pass):
            has_failed_event_required_to_pass = any(
                grade.points() / grade.max_points() < 0.5
                for grade in grades_for_events_required_to_pass
            )
            if has_failed_event_required_to_pass:
                return 'Has not passed required event'

        points = 0.0
        max_points = 0.0

        for grade in grades:
            points = points + (grade.points() * grade.event.weight)
            max_points = max_points + (grade.max_points() * grade.event.weight)

        return points / max_points * 100

    def get_final_percentage(self, group_id):
        grade_in_percent = Student.calculate_current_final(self=self, group_id=group_id)
        if isinstance(grade_in_percent, str):
            return grade_in_percent
        else:
            return f'{int(round(grade_in_percent))}%'


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    academic_degree = models.CharField(max_length=32)

    def __str__(self):
        return f'{self.academic_degree} {self.user.get_full_name()}'


class Course(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    tutor = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    def seats_count(self):
        return self.group_set.aggregate(Sum('size'))['size__sum']

    def __str__(self):
        return self.name


class Group(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    tag = models.CharField(max_length=15)
    size = models.PositiveSmallIntegerField()
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.teacher}, {self.tag}'


class CourseParticipation(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    final_grade = models.CharField(max_length=3, choices=GRADES, null=True)

    def __str__(self):
        return f'{self.student} assigned to {self.group}'


class Event(models.Model):
    name = models.CharField(max_length=100)
    date = models.DateTimeField()
    is_required_to_pass_the_course = models.BooleanField()
    min_tasks_positive = models.PositiveSmallIntegerField(default=0)
    weight = models.PositiveSmallIntegerField()
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

    def max_points(self):
        return self.task_set.aggregate(Sum('max_points'))['max_points__sum']

    def grades_statistics(self):
        if self.task_set.count() <= 0:
            return '<no tasks>'

        grades = self.grade_set.all()
        if len(grades) <= 0:
            return {'mean': '', 'variance': '', 'median': '', 'best': ''}

        avg = mean(grade.points()/grade.max_points() for grade in grades)
        medium = median(grade.points()/grade.max_points() for grade in grades)
        var = 0
        if len(grades) > 1:
            var = variance(grade.points()/grade.max_points() for grade in grades)

        max_points = 0
        for grade in grades:
            points = grade.points() / grade.max_points()
            if points > max_points:
                max_points = points

        avg = f'{int(round(avg * 100))}%'
        medium = f'{int(round(medium * 100))}%'
        var = f'{int(round(var * 100))}%'
        max_points = f'{int(round(max_points * 100))}%'

        return {'mean': avg, 'variance': var, 'median': medium, 'best': max_points}

    def average_grade(self):
        if self.task_set.count() <= 0:
            return '<no tasks>'

        grades = self.grade_set.all()
        if len(grades) <= 0:
            return '<no grades yet>'

        points_sum = sum(grade.points() for grade in grades)
        max_points_sum = len(grades) * self.max_points()

        percentage = (points_sum / max_points_sum) * 100

        return f'{int(round(percentage))}%'

    def __str__(self):
        return f'{self.name}; {self.date.date().strftime("%A %d. %B %Y")}'


class Grade(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    value = models.CharField(max_length=3, choices=GRADES, null=True)
    date_of_registration = models.DateTimeField()

    def points(self):
        min_tasks_positive = self.event.min_tasks_positive
        if min_tasks_positive > 0:
            positive_tasks_count = sum(
                task_points.points / task_points.task.max_points >= 0.5
                for task_points in self.taskpoints_set.all()
            )
            if positive_tasks_count < min_tasks_positive:
                return 0
        return self.taskpoints_set.aggregate(Sum('points'))['points__sum']

    def max_points(self):
        return self.event.max_points()

    def __str__(self):
        return f'{self.student}, {self.event}'


class Task(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    max_points = models.PositiveSmallIntegerField()

    def __str__(self):
        return f'{self.event}, {self.name}'


class TaskPoints(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    grade = models.ForeignKey(Grade, on_delete=models.CASCADE)
    points = models.PositiveSmallIntegerField()

    def __str__(self):
        return f'{self.task}, {self.points}/{self.task.max_points}'

courses/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from datetime import datetime
from django.forms import SelectDateWidget
from django.core.validators import RegexValidator
from courses.models import Teacher, Student

DEGREE_CHOICES = [
    (1, 'inż.'),
    (2, 'mgr'),
    (3, 'mgr inż.'),
    (4, 'dr'),
    (5, 'dr inż'),
    (7, 'dr hab.'),
]


def check_degree(degree):
    if degree is None:
        raise forms.ValidationError("Select your academic degree")

#
# def check_index_length(index):
#     if len(index) < 6:
#         raise forms.ValidationError("Index to short")


class SignUpStudentForm(UserCreationForm):
    index_no = forms.CharField(max_length=30, help_text='Required.',
                               validators=[RegexValidator(regex="^\d{6}$", message="Index should be 6 digits number", )])
    last_name = forms.CharField(max_length=30)
    first_name = forms.CharField(max_length=30)

    class Meta:
        model = User
        fields = ('username', 'last_name', 'first_name', 'index_no', 'password1', 'password2')


class SignUpTeacherForm(UserCreationForm):
    academic_degree = forms.CharField(widget=forms.Select(choices=DEGREE_CHOICES),
                                      help_text='Required.', validators=[check_degree, ])
    last_name = forms.CharField(max_length=30)
    first_name = forms.CharField(max_length=30)


    class Meta:
        model = User
        fields = ('username', 'last_name', 'first_name', 'academic_degree', 'password1', 'password2')


class CreateCourseForm(forms.Form):
    name = forms.CharField(max_length=200)
    description = forms.CharField(widget=forms.Textarea)


class CreateGroupForm(forms.Form):
    tag = forms.CharField(max_length=15)
    size = forms.IntegerField()
    teacher = forms.ModelChoiceField(queryset=Teacher.objects.all(), empty_label=None)


class CreateEventForm(forms.Form):
    name = forms.CharField(max_length=100)
    date = forms.DateTimeField(widget=SelectDateWidget(), initial=datetime.now())
    is_required_to_pass_the_course = forms.BooleanField(required=False)
    min_tasks_positive = forms.IntegerField(initial=0)
    weight = forms.IntegerField(initial=1)
    tasks_count = forms.IntegerField(initial=0)


class CreateTaskForm(forms.Form):
    name = forms.CharField(max_length=100)
    max_points = forms.IntegerField()


class RegisterTaskPointsForm(forms.Form):
    points = forms.IntegerField(initial=0, min_value=0)


class PickStudentForm(forms.Form):
    student = forms.ModelChoiceField(queryset=Student.objects.all())

    def __init__(self, *args, **kwargs):
        if 'students_choice_set' in kwargs:
            students_choice_set = kwargs.pop('students_choice_set')
            super(PickStudentForm, self).__init__(*args, **kwargs)
            self.fields['student'].queryset = students_choice_set
        else:
            super(PickStudentForm, self).__init__(*args, **kwargs)


class FileUploadForm(forms.Form):
    file = forms.FileField()

templates/courses/add_course.html
{% extends 'courses/layout.html' %}
{% load widget_tweaks %}
{% block content %}
    <h2>Create new course</h2>
    <form method="POST">{% csrf_token %}
        <div class="form-group">
            {{ form.name.errors }}
            <label for="{{ form.name.id_for_label }}">Course name:</label>
            {{ form.name|add_class:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.description.errors }}
            <label for="{{ form.description.id_for_label }}">Course description:</label>
            {{ form.description|add_class:"form-control" }}
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
{% endblock %}

templates/courses/add_grades.html
{% extends 'courses/layout.html' %}
{% load widget_tweaks %}
{% block content %}
    <h2>Register grade</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ points_formset.management_form }}
        <div class="form-group">
            {{ student_form.student.errors }}
            <label for="{{ student_form.student.id_for_label }}">Studeent:</label>
            {{ student_form.student|add_class:"form-control" }}
        </div>
        <table class="table table-bordered">
          <thead>
            <tr>
                {% for name in task_names %}
                  <th scope="col">{{ name }}</th>
                {% endfor %}
            </tr>
          </thead>
          <tbody>
            <tr>
                {% for form in points_formset %}
                    <td>
                        <div class="form-group">
                            {{ form.points.errors }}
                            {{ form.points|add_class:"form-control" }}
                        </div>
                    </td>
                {% endfor %}
            </tr>
          </tbody>
        </table>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
{% endblock %}

templates/courses/base.html
{% extends 'courses/layout.html' %}

{% block content %}

    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>
{% endblock %}

templates/courses/blank.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">

    <title>Hall of Fame</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-primary">
      <span class="navbar-brand mb-0 h1">Hall of Fame</span>
    </nav>


    <div class="container mt-3">
        No content yet available
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Jadwiga Uljasz & Marcin Kozubek
        </div>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/courses/course.html
{% extends 'courses/layout.html' %}
{% load widget_tweaks %}
{% block content %}
    <h2>{{ course.name }}</h2>

    <h5>Tutor:</h5>
    <p>{{ course.tutor }}</p>

    <h5>Course description:</h5>
    <p>{{ course.description }}</p>

    <h5>Groups:</h5>
    {%  if course.group_set.all %}
    <ul class="list-group">
    {% for group in course.group_set.all %}
        <li class="list-group-item">
            <a href="/courses/group/{{ group.id }}" class="text-decoration-none text-dark">{{ group }}</a>
        </li>
    {% endfor %}
    {%  else %}
            <h6 class="text-decoration-none text-dark">No group yet created.</h6>
    {% endif %}

    {%  if user.teacher %}
        <li class="list-group-item">
            <a href="/courses/{{ course.id }}/createGroup" class="btn btn-primary">Create group</a>
        </li>
    {%  endif %}
    </ul>
{% endblock %}

templates/courses/courseDetails.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'courses/style.css' %}">

    <title>Hall of Fame</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-primary">
      <span class="navbar-brand mb-0 h1">Grups of {{ course.course_name }}</span>
    </nav>

    <div class="container mt-3">
        <div class="row mt-3">
            <div class="col">
            {% if course %}
                <ul class="list-group">
                {% for group in course.group_set.all %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-10">{{ group.group_tag }}</div>
                            <div class="col-8">Student limit: {{ group.size }}</div>
                            <div class="col-2 text-secondary text-right">teacher: </div>
                        </div>
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                <p>No courses are available</p>
            {% endif %}
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Jadwiga Uljasz & Marcin Kozubek
        </div>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/courses/courses_list.html
{% extends 'base.html' %}

{% block content %}
  <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
  <ul>
  {% for user in filter.qs %}
    <li>{{ user.username }} - {{ user.get_full_name }}</li>
  {% endfor %}
  </ul>
{% endblock %}

templates/courses/create_group.html
{% extends 'courses/layout.html' %}
{% load widget_tweaks %}
{% block content %}
    <h2>Create new group</h2>
    <form method="POST">{% csrf_token %}
        <div class="form-group">
            {{ form.tag.errors }}
            <label for="{{ form.tag.id_for_label }}">Group tag:</label>
            {{ form.tag|add_class:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.size.errors }}
            <label for="{{ form.size.id_for_label }}">Size:</label>
            {{ form.size|add_class:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.teacher.errors }}
            <label for="{{ form.teacher.id_for_label }}">Teacher:</label>
            {{ form.teacher|add_class:"form-control" }}
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
{% endblock %}

templates/courses/grades.html
{% extends 'courses/layout.html' %}

{% block content %}
<h2>My grades: </h2>
<div class="row mt-3">
    <div class="col">
    {% if grades %}
        <ul class="list-group">
        {% for event, grade in grades %}
        <li class="list-group-item">
            {{ event }}: {{ grade }}
        </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>You don't have any grades</p>
    {% endif %}
    </div>
</div>
{% endblock %}

templates/courses/group.html
{% extends 'courses/layout.html' %}
{% load widget_tweaks %}
{% block content %}
    <h2>{{ group.course.name }}, {{ group.tag }}</h2>

    <h5>Teacher:</h5>
    <p>{{ group.teacher }}</p>

    <h5>Seats taken:</h5>
    <p>{{ group.courseparticipation_set.count }}/{{ group.size }}</p>

    <h5>Events:</h5>
    {%  if not group.event_set.all  %}
        <h6>No events yet.</h6>
    {%  endif %}
    {% for event in group.event_set.all %}
        <li class="list-group-item">
        <div class="row">
            <div class="col-6">{{ event }}</div>
            {% if event.task_set.count > 0 %}
                {% if user.teacher %}
                    <div class="col-2"><a href="/addGrades/{{ event.id }}" class="btn btn-primary">Add grades</a></div>
                    <div class="col-4">
                        <form class="form-inline" action="/courses/uploadGrades/{{ event.id }}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-8">
                                    {{ file_upload_form.file }}
                                </div>
                                <div class="col-4">
                                    <button type="submit" class="btn btn-outline-primary">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                {% else %}
                    <div class="row">
                        <ul>
                          <li>
                              Average points: <b>{{ event.grades_statistics.mean }}</b>
                          </li>
                          <li>
                              Variance of points: <b>{{ event.grades_statistics.variance }}</b>
                          </li>
                          <li>
                              Median of points: <b>{{ event.grades_statistics.median }}</b>
                          </li>
                          <li>
                              Best result: <b>{{ event.grades_statistics.best }}</b>
                          </li>
                        </ul>
                    </div>
                {% endif %}
             {% endif %}
        </div>
        </li>
    {% endfor %}
    <ul class="list-group">
        <li class="list-group-item">
            {% if user.teacher %}
            <a href="/courses/group/{{ group.id }}/createEvent" class="btn btn-primary">Create event</a>
            {% endif %}
                {% if user.student %}
                 <form method ='POST' id= 'join' action="{% url 'HallOfFame:join' group.id %}" >
                    {% csrf_token %}
                         <button type="submit">Join</button>
                 <input type="hidden" >
 </form>

            {% endif %}
        </li>

    </ul>

    <h5 class="mt-3">Members:</h5>
{#    {% if members.count > 0 %}#}
        <ul>
        {% for member, grade in members %}
            <li>
                {{ member }}, current final: {{ grade }}
            </li>
        {% endfor %}
        </ul>
    <h4>
        Number of students passing: {{ passing_students }}
    </h4>
    <h4>
            Mean grade: {{ mean_grade }}
    </h4>
{#    {% else %}#}
{#        <p>Group has no members</p>#}
{#    {% endif %}#}
{% endblock %}

templates/courses/index.html
{% extends 'courses/layout.html' %}

{% block content %}
    {% if not user.is_authenticated %}
      <p>Your account doesn't have access to this page. To proceed,
      please login with an account that has access.</p>
    {% else %}
<h2>Courses: </h2>
<div class="row mt-3">
    <div class="col">
        <ul class="list-group">
            {% if user.teacher %}
                <li class="list-group-item">
                    <a href="/courses/createCourse" class="btn btn-primary">Create course</a>
                </li>
            {% endif %}

        <h4>Search parameters: </h4>
         <form method="GET" action=".">
        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="name_contains" placeholder="Course name contains..." />
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-12">
                <div class="input-group">
                    <input class="form-control py-2 border-right-0 border" type="search" name="description" placeholder="Description contains..." />
                    <span class="input-group-append">
                        <div class="input-group-text bg-transparent">
                            <i class="fa fa-search"></i>
                        </div>
                    </span>
                </div>
            </div>
        </div>

             <div class="form-group col-md-4">
            <label for="teacher">Tutor</label>
            <select id="teacher" class="form-control" name="teacher">
              <option selected>Choose...</option>
              {% for teacher in teachers %}
              <option value="{{ teacher.user_id }}">{{ teacher  }}</option>
              {% endfor %}
            </select>
          </div>
        <button type="submit" class="btn btn-primary">Search</button>
      </form>
        <h2>Courses: </h2>
            {% if courses %}
          {% for course in filter.qs %}
            <a href="/courses/{{ course.id }}" class="text-decoration-none text-dark">
                <div class="row">
                    <div class="col-10">{{ course.name }}</div>
                    <div class="col-2 text-secondary text-right">seats: {{ course.seats_count }}</div>
                </div>
            </a>
          {% endfor %}
        {% for course in courses %}
        <li class="list-group-item">
            <a href="/courses/{{ course.id }}" class="text-decoration-none text-dark">
                <div class="row">
                    <div class="col-10">{{ course.name }}</div>
                    <div class="col-2 text-secondary text-right">seats: {{ course.seats_count }}</div>
                </div>
            </a>
        </li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No such courses are available</p>
    {% endif %}
    </div>
</div>
    {%  endif %}
{% endblock %}